// Interface automatically generated by schemas-to-ts

import { User } from '../../../../common/schemas-to-ts/User';
import { User_Plain } from '../../../../common/schemas-to-ts/User';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Emotions {
  Angry = 'ANGRY',
  Sad = 'SAD',
  Calm = 'CALM',
  Worried = 'WORRIED',
  Happy = 'HAPPY',
  Embarrassed = 'EMBARRASSED',
  Uncomfortable = 'UNCOMFORTABLE',
  Confused = 'CONFUSED',
  Bored = 'BORED',
  Excited = 'EXCITED',
  Relaxed = 'RELAXED',}

export interface Emotion {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    emotions: Emotions;
    entry: string;
    user?: { data: User };
  };
}
export interface Emotion_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  emotions: Emotions;
  entry: string;
  user?: User_Plain;
}

export interface Emotion_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  emotions: Emotions;
  entry: string;
  user?: number;
}

export interface Emotion_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  emotions: Emotions;
  entry: string;
  user?: AdminPanelRelationPropertyModification<User_Plain>;
}
